server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: authservice
        # uri: http://localhost:8081
        uri: http://authservice:8081
        predicates:
        - Path=/api/auth/**
      - id: userservice
        # uri: http://localhost:8082
        uri: http://userservice:8082
        predicates:
        - Path=/api/user/**
